version: "3.2"
services:
  postgres:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=enroll-task
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    expose:
     - "5432"
  backend:
    build:
      dockerfile: ./docker/be/Dockerfile
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    expose:
     - "4000"
    volumes:
      - ./:/app
    working_dir: /app
    command: mix start
  frontend:
    build:
      dockerfile: ./docker/fe/Dockerfile
    depends_on:
      - postgres
    ports:
      - "5005:5005"
    expose:
     - "5005"
    volumes:
      - ./:/app
    working_dir: /app/frontend
    command: sh -c "yarn install && yarn start:local"
volumes:
  pgdata:
